services:
  series-renamer:
    build: .
    container_name: series-renamer
    env_file:
      - .env
    ports:
      - "8085:8085"
    environment:
      APP_DATA_DIR: /config/series-renamer
    volumes:
      - /opt/appdata/jellyfin:/config
      - /mnt/storage/movies:/media/movies
      - /mnt/storage/series:/media/series
      - /mnt/storage/cristaos:/media/cristaos
      - /mnt/storage/Livros:/media/livros
      - /mnt/storage/Audio-livros:/media/Audio-livros
    restart: unless-stopped
